CREATE DATABASE IF NOT EXISTS DEMO_TRANSFER DEFAULT CHARSET utf8 COLLATE utf8_general_ci;
USE DEMO_TRANSFER;
CREATE TABLE IF NOT EXISTS `transfer_record`(
`id` INT UNSIGNED AUTO_INCREMENT,
`out` VARCHAR(40) NOT NULL,
`in` VARCHAR(40) NOT NULL,
`money` DOUBLE(8,2),
PRIMARY KEY(`id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
